// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbIUy9D_V8XOQhjAANVwcumGZtWbALJw',
    appId: '1:908434646252:web:ff1f7f30f48d744f7eb1c9',
    messagingSenderId: '908434646252',
    projectId: 'exanor-user-app',
    authDomain: 'exanor-user-app.firebaseapp.com',
    storageBucket: 'exanor-user-app.firebasestorage.app',
    measurementId: 'G-MEKE4M6HSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC65jNDCzPsPEmnIa-TQ3Kp7WUIytzFdUE',
    appId: '1:908434646252:android:6bbf74c16569c0df7eb1c9',
    messagingSenderId: '908434646252',
    projectId: 'exanor-user-app',
    storageBucket: 'exanor-user-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR0TPNMw9K3wWdgGTYpkocQS7yrac0j8',
    appId: '1:908434646252:ios:3432b0e4769df0447eb1c9',
    messagingSenderId: '908434646252',
    projectId: 'exanor-user-app',
    storageBucket: 'exanor-user-app.firebasestorage.app',
    iosBundleId: 'com.exanor.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR0TPNMw9K3wWdgGTYpkocQS7yrac0j8',
    appId: '1:908434646252:ios:3432b0e4769df0447eb1c9',
    messagingSenderId: '908434646252',
    projectId: 'exanor-user-app',
    storageBucket: 'exanor-user-app.firebasestorage.app',
    iosBundleId: 'com.exanor.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmbIUy9D_V8XOQhjAANVwcumGZtWbALJw',
    appId: '1:908434646252:web:01fe6493a2714ee17eb1c9',
    messagingSenderId: '908434646252',
    projectId: 'exanor-user-app',
    authDomain: 'exanor-user-app.firebaseapp.com',
    storageBucket: 'exanor-user-app.firebasestorage.app',
    measurementId: 'G-F1PZS3WLN0',
  );

}