/*

This page is depricitaed and is not under use and is not deleted because of
dependencies issues... please do not edit this file...

Wait, the user IS using this matching the flow from PhoneRegistrationScreen which pushes to OTPVerificationScreen. 
I must update it.

*/

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:exanor/components/otp_input_section.dart';
import 'package:exanor/screens/HomeScreen.dart';
import 'package:exanor/screens/account_completion_screen.dart';
import 'package:exanor/services/api_service.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:exanor/components/translation_widget.dart';
import 'package:exanor/components/universal_translation_wrapper.dart';
import 'package:exanor/services/enhanced_translation_service.dart';

class OTPVerificationScreen extends StatefulWidget {
  final String phoneNumber;

  const OTPVerificationScreen({super.key, required this.phoneNumber});

  @override
  State<OTPVerificationScreen> createState() => _OTPVerificationScreenState();
}

class _OTPVerificationScreenState extends State<OTPVerificationScreen> {
  String _otpCode = '';
  bool _isLoading = false;
  bool _isResendLoading = false;
  int _resendTimer = 60;
  Timer? _timer;
  bool _canResend = false;

  // Enhanced translation service
  final EnhancedTranslationService _enhancedTranslation =
      EnhancedTranslationService.instance;

  @override
  void initState() {
    super.initState();
    _startResendTimer();
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  void _startResendTimer() {
    setState(() {
      _resendTimer = 60;
      _canResend = false;
    });

    _timer?.cancel();
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (_resendTimer > 0) {
        setState(() {
          _resendTimer--;
        });
      } else {
        setState(() {
          _canResend = true;
        });
        timer.cancel();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: theme.colorScheme.onSurface),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: UniversalTranslationWrapper(
        excludePatterns: const ['+', '@', '.com', 'OTP', 'API'],
        child: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.symmetric(horizontal: 24.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      const SizedBox(height: 20),

                      // Animated Lock Icon (Subtle)
                      Center(
                        child: Container(
                          width: 80,
                          height: 80,
                          decoration: BoxDecoration(
                            color: theme.colorScheme.primary.withOpacity(0.1),
                            shape: BoxShape.circle,
                          ),
                          child: Icon(
                            Icons.lock_person_rounded,
                            size: 32,
                            color: theme.colorScheme.primary,
                          ),
                        ),
                      ),

                      const SizedBox(height: 32),

                      TranslatedText(
                        'Verification Code',
                        style: theme.textTheme.headlineMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                          color: theme.colorScheme.onSurface,
                          letterSpacing: -0.5,
                        ),
                        textAlign: TextAlign.center,
                      ),

                      const SizedBox(height: 12),

                      RichText(
                        textAlign: TextAlign.center,
                        text: TextSpan(
                          style: theme.textTheme.bodyLarge?.copyWith(
                            color: theme.colorScheme.onSurface.withOpacity(0.6),
                          ),
                          children: [
                            const TextSpan(
                              text: "We have sent the verification code to\n",
                            ),
                            TextSpan(
                              text: widget.phoneNumber,
                              style: TextStyle(
                                color: theme.colorScheme.onSurface,
                                fontWeight: FontWeight.w600,
                                fontSize: 18,
                                height: 1.5,
                              ),
                            ),
                          ],
                        ),
                      ),

                      const SizedBox(height: 48),

                      // OTP Input
                      OTPInputSection(
                        otpCode: _otpCode,
                        onChanged: (code) {
                          setState(() {
                            _otpCode = code;
                          });
                        },
                      ),

                      const SizedBox(height: 48),

                      // Verify Button
                      Container(
                        width: double.infinity,
                        height: 56,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(16),
                          boxShadow: [
                            BoxShadow(
                              color: theme.colorScheme.primary.withOpacity(0.3),
                              blurRadius: 20,
                              offset: const Offset(0, 8),
                            ),
                          ],
                        ),
                        child: ElevatedButton(
                          onPressed: _otpCode.length == 4 ? _verifyOTP : null,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: theme.colorScheme.primary,
                            foregroundColor: Colors.white,
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16),
                            ),
                            disabledBackgroundColor:
                                theme.colorScheme.surfaceContainerHigh,
                          ),
                          child: _isLoading
                              ? const SizedBox(
                                  width: 24,
                                  height: 24,
                                  child: CircularProgressIndicator(
                                    color: Colors.white,
                                    strokeWidth: 2.5,
                                  ),
                                )
                              : TranslatedText(
                                  'Verify',
                                  style: theme.textTheme.titleMedium?.copyWith(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                    letterSpacing: 0.5,
                                  ),
                                ),
                        ),
                      ),

                      const SizedBox(height: 32),

                      // Resend Code
                      Center(
                        child: _canResend
                            ? GestureDetector(
                                onTap: _resendCode,
                                child: Text(
                                  'Resend Code',
                                  style: theme.textTheme.bodyLarge?.copyWith(
                                    color: theme.colorScheme.primary,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              )
                            : RichText(
                                text: TextSpan(
                                  style: theme.textTheme.bodyMedium?.copyWith(
                                    color: theme.colorScheme.onSurface
                                        .withOpacity(0.5),
                                  ),
                                  children: [
                                    const TextSpan(text: 'Resend code in '),
                                    TextSpan(
                                      text: '${_resendTimer}s',
                                      style: TextStyle(
                                        color: theme.colorScheme.primary,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _resendCode() async {
    if (!_canResend || _isResendLoading) return;

    setState(() {
      _isResendLoading = true;
    });

    try {
      String phoneNumber = widget.phoneNumber;

      print('🔄 Resending OTP to: $phoneNumber');

      final response = await ApiService.post(
        '/send-otp/',
        body: {'phone_number': phoneNumber},
      );

      if (mounted) {
        setState(() {
          _isResendLoading = false;
        });

        if (response['data'] != null && response['data']['status'] == 200) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: TranslatedText('Verification code sent!')),
          );
          _startResendTimer();
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const TranslatedText(
                'Failed to resend OTP. Please try again.',
              ),
              backgroundColor: Theme.of(context).colorScheme.error,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isResendLoading = false;
        });
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const TranslatedText('Network error. Please try again.'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    }
  }

  void _verifyOTP() async {
    setState(() {
      _isLoading = true;
    });

    try {
      String phoneNumber = widget.phoneNumber;

      final response = await ApiService.post(
        '/user-sign-up/',
        body: {
          'phone_number': phoneNumber,
          'otp': _otpCode,
          'signup': true,
          'is_app': true, // Added flag to receive refresh token
        },
      );

      if (mounted) {
        setState(() {
          _isLoading = false;
        });

        if (response['data'] != null) {
          final responseData = response['data'];
          final status = responseData['status'];
          final message = responseData['message'] as String?;

          final statusCode = status is int
              ? status
              : int.tryParse(status.toString());

          if (statusCode == 200) {
            if (responseData['access_token'] != null) {
              // Store tokens including the new refresh token
              await ApiService.storeTokens(
                accessToken: responseData['access_token'],
                refreshToken:
                    responseData['refresh_token'], // Capture refresh token
                csrfToken: responseData['csrf_token'],
              );
            }
            if (responseData['user_data'] != null) {
              await _storeUserData(responseData['user_data']);
            }

            // Check for profile completion for both login and signup
            final userData = responseData['user_data'];
            final firstName = userData?['first_name'] as String?;
            final lastName = userData?['last_name'] as String?;
            final gender = userData?['gender'] as String?;

            final needsProfileCompletion =
                firstName == 'unnamed' ||
                lastName == 'user' ||
                gender == 'undefined' ||
                firstName == null ||
                firstName.isEmpty ||
                lastName == null ||
                gender == null;

            if (message == 'Login successful' || message == 'User created') {
              if (needsProfileCompletion) {
                // Profile incomplete - redirect to completion screen
                Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(
                    builder: (context) => AccountCompletionScreen(
                      accessToken: responseData['access_token'],
                      csrfToken: responseData['csrf_token'],
                      userData: userData ?? {},
                    ),
                  ),
                  (route) => false,
                );
              } else {
                // Profile complete - go to home
                Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(builder: (context) => const HomeScreen()),
                  (route) => false,
                );
              }
            } else {
              _showErrorSnackBar(
                message ?? 'Verification failed. Please try again.',
              );
            }
          } else {
            _showErrorSnackBar(
              message ?? 'Verification failed. Please try again.',
            );
          }
        } else {
          _showErrorSnackBar('Invalid response format.');
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
        _showErrorSnackBar('OTP verification failed. Please try again.');
      }
    }
  }

  Future<void> _storeUserData(Map<String, dynamic> userData) async {
    try {
      final prefs = await SharedPreferences.getInstance();

      if (userData['id'] != null) {
        await prefs.setString('user_id', userData['id']);
      }
      if (userData['first_name'] != null) {
        await prefs.setString('first_name', userData['first_name']);
      }
      if (userData['last_name'] != null) {
        await prefs.setString('last_name', userData['last_name']);
      }
      if (userData['phone_number'] != null) {
        await prefs.setString(
          'phone_number',
          userData['phone_number'].toString(),
        );
      }
      if (userData['email'] != null) {
        await prefs.setString('email', userData['email']);
      }
      if (userData['img_url'] != null) {
        await prefs.setString('img_url', userData['img_url']);
      }
      if (userData['gender'] != null) {
        await prefs.setString('gender', userData['gender']);
      }
      if (userData['address_line_1'] != null) {
        await prefs.setString('address_line_1', userData['address_line_1']);
      }
      if (userData['address_line_2'] != null) {
        await prefs.setString('address_line_2', userData['address_line_2']);
      }
      if (userData['city'] != null) {
        await prefs.setString('city', userData['city']);
      }
      if (userData['state'] != null) {
        await prefs.setString('state', userData['state']);
      }
      if (userData['pincode'] != null) {
        await prefs.setInt('pincode', userData['pincode']);
      }
      if (userData['lat'] != null) {
        await prefs.setString('lat', userData['lat']);
      }
      if (userData['lng'] != null) {
        await prefs.setString('lng', userData['lng']);
      }
    } catch (e) {
      print('❌ Error storing user data: $e');
    }
  }

  void _showErrorSnackBar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: TranslatedText(message),
        backgroundColor: Theme.of(context).colorScheme.error,
        duration: const Duration(seconds: 3),
      ),
    );
  }
}
